In [2]:
import torch
print(torch.__version__)
print(torch.__path__)

1.12.1
['/Users/pierreloviton/opt/anaconda3/lib/python3.9/site-packages/torch']


## Torch Tensors

### Creating a tensor

In [3]:
x = torch.tensor([[5.5, 3],[2, 1]], dtype=torch.float32) # --- or float
x = torch.tensor([[5.5, 3],[2, 1]], dtype=torch.float64) # --- or double
print(x)
print(x.size())

tensor([[5.5000, 3.0000],
        [2.0000, 1.0000]], dtype=torch.float64)
torch.Size([2, 2])


In [4]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)   # --- ues '-1' when you want the relative shape to be infered automaticallly
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Various ways of creating tensors

In [6]:
%pylab
import torch.nn

x = torch.arange(-10, 10, 0.1)
plot(x.numpy(), torch.nn.Tanh()(x).numpy());
plot(x.numpy(), torch.nn.functional.tanh(x).numpy());

x = torch.Tensor(2, 3)
x = torch.rand(2, 3)
x = torch.randn(2, 3)
x = torch.eye(3)
x = torch.ones(10)
x = torch.ones(2,3)
x = torch.zeros(10)
x = torch.ones_like(x)
x = torch.arange(5)
x = torch.arange(0, 5, step=1)
x = torch.linspace(1, 10, steps=10)
x = torch.logspace(start=-10, end=10, steps=5)

x.size()
torch.numel(x)    # get the total number of elements in the tensor

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


/Users/pierreloviton/opt/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py:1949: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


5

## Tensor Dimensions

In [15]:
v = torch.arange(0,6).view(2,3)
v

tensor([[0, 1, 2],
        [3, 4, 5]])

In [17]:
v[0]    # --- return the first row

tensor([0, 1, 2])

In [18]:
v[0][2] # --- second elements in first row

tensor(2)

In [23]:
v[0,2]  # --- same as above

tensor(2)

In [20]:
v[0,:]    # --- return all elements of the first row

tensor([0, 1, 2])

In [21]:
v[:,0]    # --- return all elements of the first column

tensor([0, 2])

In [24]:
v[1].fill_(2)   # --- fill with a 2 the 2nd line

tensor([2, 2, 2])

## From / To numpy

### Torch to Numpy: .numpy()

In [26]:
a = torch.ones(2,5, dtype=torch.float64)
b = a.numpy()

print(type(b))

print(b.dtype)

print(b)

<class 'numpy.ndarray'>
float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Numpy to Torch: .from_numpy()

In [31]:
a = np.ones((2,5)) # --- by default uses dtype=np.float64
a = np.ones((2,5), dtype=np.int32)
b = torch.from_numpy(a)  
print(a)

np.add(a, 1, out=a)  # --- add 1 to a

print(a)

print(b)

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[2 2 2 2 2]
 [2 2 2 2 2]]
tensor([[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]], dtype=torch.int32)


## Operators

### Addition

x = torch.Tensor(2, 3)
y = torch.rand(2, 3)

z1 = x + y
z2 = torch.add(x, y)

r1 = torch.Tensor(2, 3)
torch.add(x, y, out=r1)

In [65]:
x.add_(y)   # Same as x = x + y

tensor([[6.2509e-01, 8.5899e+09, 1.3019e+00],
        [1.0309e+00, 7.7303e-01, 7.1378e-01]])

## Matrix operators

### Dot product of 2 tensors: torch.dot

In [72]:
vec1 = torch.ones(10)
vec2 = 2*torch.ones(10)
r = torch.dot(vec1,vec2)
r = vec1 @ vec2

In [76]:
print(vec1.size())

torch.Size([10])


In [74]:
print(vec2.size())

torch.Size([10])


In [75]:
print(r)

tensor(20.)


### Matrix, vector products: torch.mv

In [81]:
mat = torch.randn(2, 4)
vec = torch.randn(4)
r = torch.mv(mat, vec)
r = mat @ vec

print(r.size())

torch.Size([2])


### Matrix, Matrix products: torch.mm

In [90]:
mat1 = torch.ones(5,10)
mat2 = torch.ones(10,20)
r = torch.mm(mat1, mat2)
r = mat1 @ mat2

In [91]:
print(mat1.size())

torch.Size([5, 10])


In [92]:
print(mat2.size())

torch.Size([10, 20])


In [94]:
print(r.size())

torch.Size([5, 20])


### Element-wise multiplication.mul

In [95]:
mat1 = torch.ones(5,10)
mat2 = 2*torch.ones(5,10)
r = torch.mul(mat1,mat2)
r = mat1 * mat2

print(r.size())

torch.Size([5, 10])


### torch.matmul

### Broadcasting

In [96]:
matA = torch.ones(5,10)
matB = torch.ones(5,1)
print( (matA + matB).size() )

torch.Size([5, 10])


In [97]:
matA = torch.ones(5,10)
vecB = torch.ones(5)
print( (matA + vecB).size() )

RuntimeError: The size of tensor a (10) must match the size of tensor b (5) at non-singleton dimension 1

In [98]:
matA = torch.ones(5,10)
matC = torch.ones(1,10)
print( (matA + matC).size() )

torch.Size([5, 10])


In [99]:
matA = torch.ones(5,10)
vecC = torch.ones(10)
print( (matA + vecC).size() )

torch.Size([5, 10])


## Autograd